# 立ち上げる
# docker-compose up --build

# container を落とすと Metadata は消去される
# docker-compose down

version: "3.6"
services:
  postgres: # 必須
    ports:
      - 5432:5432
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine: # postgres を立ち上げるだけなら、なくてもいい
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
